name: Workflow
on: [push]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn, Build and Lint
        run: |
          yarn
          yarn lint
          yarn build
        env:
          CI: true
